import type { Account, GoalAccount, Transaction } from './types';

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'savings-1',
    ownerName: 'William Roskær',
    iban: 'NL20 TRIO 2301 2295 21',
    balance: 8200,
    type: 'savings',
  },
  {
    id: 'checking-1',
    ownerName: 'William Roskær',
    iban: 'NL10 TRIO 7210 0235 21',
    balance: 3100,
    type: 'checking',
  },
];

export const INITIAL_GOALS: GoalAccount[] = [
  // ── Saving goals ─────────────────────────────────────────────────────────────
  {
    id: 'goal-1',
    name: 'Solar panels',
    iconKey: 'home',
    transition: 'energy',
    partnershipId: 'solarnl',
    balance: 1000,
    targetAmount: 8000,
    parentAccountId: 'savings-1',
    purpose: 'Become energy independent at home',
    goalType: 'saving',
  },
  {
    id: 'goal-2',
    name: 'Gazelle e-bike',
    iconKey: 'bike',
    transition: 'resources',
    partnershipId: 'gazelle',
    balance: 500,
    targetAmount: 2500,
    parentAccountId: 'savings-1',
    purpose: 'Get around sustainably without a car',
    goalType: 'saving',
  },
  {
    id: 'goal-3',
    name: 'Veggie garden',
    iconKey: 'garden',
    transition: 'food',
    balance: 300,
    targetAmount: 600,
    parentAccountId: 'savings-1',
    purpose: 'Grow my own vegetables',
    goalType: 'saving',
  },
  {
    id: 'goal-4',
    name: 'Emergency fund',
    iconKey: 'safety',
    transition: 'society',
    balance: 800,
    targetAmount: 2000,
    parentAccountId: 'savings-1',
    purpose: 'Build financial resilience',
    goalType: 'saving',
  },
  {
    id: 'goal-5',
    name: 'Yoga retreat',
    iconKey: 'health',
    transition: 'wellbeing',
    balance: 200,
    targetAmount: 800,
    parentAccountId: 'savings-1',
    purpose: 'Rest and recharge',
    goalType: 'saving',
  },

  // ── Investing goals — real Triodos Investment Management funds ────────────────
  {
    id: 'inv-1',
    name: 'Renewables Europe',
    iconKey: 'home',
    transition: 'energy',
    balance: 2200,
    targetAmount: 5000,
    parentAccountId: 'savings-1',
    purpose: 'Triodos Renewables Europe Fund — invests in wind, solar and hydro projects across Europe',
    goalType: 'investing',
  },
  {
    id: 'inv-2',
    name: 'Pioneer Impact',
    iconKey: 'bike',
    transition: 'resources',
    balance: 900,
    targetAmount: 3500,
    parentAccountId: 'savings-1',
    purpose: 'Triodos Pioneer Impact Fund — backs innovative companies leading the circular economy transition',
    goalType: 'investing',
  },
  {
    id: 'inv-3',
    name: 'Organic Growth',
    iconKey: 'garden',
    transition: 'food',
    balance: 1400,
    targetAmount: 2000,
    parentAccountId: 'savings-1',
    purpose: 'Triodos Organic Growth Fund — finances organic food producers and sustainable agriculture',
    goalType: 'investing',
  },
  {
    id: 'inv-4',
    name: 'Microfinance Fund',
    iconKey: 'education',
    transition: 'society',
    balance: 1800,
    targetAmount: 4000,
    parentAccountId: 'savings-1',
    purpose: 'Triodos Microfinance Fund — provides financial services to underserved communities worldwide',
    goalType: 'investing',
  },
  {
    id: 'inv-5',
    name: 'Future Generations',
    iconKey: 'health',
    transition: 'wellbeing',
    balance: 600,
    targetAmount: 1500,
    parentAccountId: 'savings-1',
    purpose: 'Triodos Future Generations Fund — long-term investments in a world fit for future generations',
    goalType: 'investing',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 't1',  label: 'Albert Heijn',       sublabel: 'Groceries',         amount: -43.80,  date: 'Today',     type: 'debit',  icon: '🛒' },
  { id: 't2',  label: 'Salary — Triodos',   sublabel: 'Monthly income',    amount: 5400.00, date: 'Today',     type: 'credit', icon: '💼' },
  { id: 't3',  label: 'NS Reizen',          sublabel: 'Public transport',  amount: -21.50,  date: 'Yesterday', type: 'debit',  icon: '🚆' },
  { id: 't4',  label: 'Thuisbezorgd',       sublabel: 'Food delivery',     amount: -18.95,  date: 'Yesterday', type: 'debit',  icon: '🍕' },
  { id: 't5',  label: 'Vattenfall',         sublabel: 'Energy bill',       amount: -94.00,  date: '6 May',     type: 'debit',  icon: '⚡' },
  { id: 't6',  label: 'S. de Vries',        sublabel: 'Transfer received', amount: 150.00,  date: '6 May',     type: 'credit', icon: '↙' },
  { id: 't7',  label: 'Picnic',             sublabel: 'Groceries',         amount: -37.20,  date: '5 May',     type: 'debit',  icon: '🛒' },
  { id: 't8',  label: 'Spotify',            sublabel: 'Subscription',      amount: -10.99,  date: '4 May',     type: 'debit',  icon: '🎵' },
  { id: 't9',  label: 'Gemeente Amsterdam', sublabel: 'Municipal tax',     amount: -56.00,  date: '3 May',     type: 'debit',  icon: '🏛️' },
  { id: 't10', label: 'Freelance payment',  sublabel: 'Invoice #2024-011', amount: 480.00,  date: '2 May',     type: 'credit', icon: '📄' },
];
